= scms-github-action

Checks a repository for scms compatibility.

Can commit into a branch of your repository, using your `username <username@users.noreply.github.com>` as committer id.

== Inputs

=== `parallelity`

Set parallelity.
The default is `"1"` which is single threaded.
Note that parallelity will fail-at-end and result in unordered log outputs.

Note: this parameter loosely follows the maven syntax. Use `1C` for one thread per core,
use `12` for exactly 12 threads and `0.9C` for rounded 0.9 threads per core.

=== `verbose`

Sets the verbosity.
The default is `INFO` for scms classes and `WARN` for 3rd-party libraries.
Use `true` for verbose output (`DEBUG` for all messages).

=== `inputpath`

Set the input path relative to the repository.
Please note that absolute paths and paths containing `/..` or `../` will be rejected.

=== `outputbranch`

If set, the results will be pushed to the specified output branch.

=== `emptycommit`

If set to `true`, the result will be committed even if the output has not changed since the previous commit.

Only effective when `outputbranch` is set.

=== `wipeoutputbranch`

*NOT IMPLEMENTED*

If set, wipes the output branch before checking in.
This will disable any diffs.

Only effective when `outputbranch` is set.


== Outputs

None yet.

== Example usage

[source,yaml]
----
steps:
- name: check with scms
  uses: scms/scms-github-action@v1
  with:
    parallelity: 1C
    verbose: true
    inputpath: site
    outputbranch: site-staging
    wipeoutputbranch: false # default
    emptycommit: true
----

== Example repository

See https://github.com/scms/scms-example[scms/scms-example].

It has two actions:

. a non-committing action
. a committing action, which commits into the https://github.com/scms/scms-example/tree/site-staging[site-staging] tree
